# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateField(auto_now_add=True, verbose_name='\u5237\u5361\u65e5\u671f')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5237\u5361\u91d1\u989d')),
                ('user', models.CharField(max_length=20, verbose_name='\u5237\u5361\u4eba')),
                ('bank', models.CharField(max_length=100, verbose_name='\u5361\u884c')),
                ('bill_date', models.DateField(verbose_name='\u8d26\u5355\u65e5')),
                ('return_date', models.DateField(verbose_name='\u8fd8\u6b3e\u65e5')),
            ],
        ),
    ]
