# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-15 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170609_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u6709\u6548')),
            ],
            options={
                'verbose_name': '\u63a8\u8350\u4fe1\u606f',
                'verbose_name_plural': '\u63a8\u8350\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='key_id',
            field=models.CharField(default=None, max_length=10, verbose_name='\u63a8\u8350\u7801'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referee_number',
            field=models.IntegerField(default=0, verbose_name='\u63a8\u8350\u4eba\u4e2a\u6570'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='referee',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee', to=settings.AUTH_USER_MODEL, verbose_name='\u63a8\u8350\u4eba'),
        ),
        migrations.AddField(
            model_name='referee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='\u88ab\u63a8\u8350\u4eba'),
        ),
    ]
