# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-16 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170616_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referee_number',
        ),
    ]
