# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-16 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userprofile_referee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referee_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referee_number',
            field=models.IntegerField(default=0, verbose_name='\u63a8\u8350\u4eba\u4e2a\u6570'),
        ),
    ]
