# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_key_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referee_key',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='\u63a8\u8350\u4ebaKey'),
        ),
    ]
