# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-09 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='\u5546\u54c1ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u540d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5355\u4ef7')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u4fe1\u606f',
                'verbose_name_plural': '\u5546\u54c1\u4fe1\u606f',
            },
        ),
    ]
