# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-09 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('completed', '\u5df2\u5b8c\u6210'), ('pending', '\u5f85\u5904\u7406'), ('closed', '\u5df2\u5173\u95ed')], max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
