# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170609_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=1, verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('completed', '\u5df2\u5b8c\u6210'), ('pending', '\u5f85\u5904\u7406'), ('closed', '\u5df2\u5173\u95ed')], default='\u5f85\u5904\u7406', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
