# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-16 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170615_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='License_plate',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='\u8f66\u724c'),
        ),
        migrations.AddField(
            model_name='order',
            name='motorcycle_type',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='\u8f66\u578b'),
        ),
        migrations.AddField(
            model_name='order',
            name='real_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='\u6210\u4ea4\u4ef7\u683c'),
        ),
    ]
