# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-16 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170616_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='License_plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u8f66\u724c'),
        ),
        migrations.AlterField(
            model_name='order',
            name='motorcycle_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u8f66\u578b'),
        ),
    ]
