# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-22 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_rebate_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rebate_amount',
        ),
    ]
