# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-02 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_rebate_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
